# Convert both
all:
		pandoc syntax.md -t beamer -V fontsize=9pt -o syntax.pdf
		pandoc syntax.md -t html5 -s -o syntax.html
		cp syntax.html /home/daniel/page/lecture-notes/web-dev/
		cp syntax.pdf /home/daniel/page/lecture-notes/web-dev/
