# Convert both
all:
		pandoc prozess.md -t beamer -V fontsize=9pt -o prozess.pdf
		pandoc prozess.md -t html5 -s -o prozess.html
		cp prozess.html /home/daniel/page/lecture-notes/web-dev/
		cp prozess.pdf /home/daniel/page/lecture-notes/web-dev/
